/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retorna o estado operacional minimo da API. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API operacional. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @enum {string} */
                                status: "ok";
                                checks: {
                                    /** @enum {string} */
                                    database: "ok";
                                };
                                /** Format: date-time */
                                checked_at: string;
                            };
                        };
                    };
                };
                /** @description API degradada. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                /** @enum {string} */
                                status: "degraded";
                                checks: {
                                    /** @enum {string} */
                                    database?: "error";
                                };
                                /** Format: date-time */
                                checked_at: string;
                            };
                        } & components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gera token CSRF para mutacoes autenticadas por cookie. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token CSRF. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                csrf_token: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cria sessao Rails via Devise. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Login efetuado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /** Encerra sessao atual. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout efetuado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                signed_out?: boolean;
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados publicos para home do marketplace. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Home publica. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                categories: components["schemas"]["ServiceCategory"][];
                                popular_services: components["schemas"]["ServiceCategory"][];
                                top_professionals: components["schemas"]["Professional"][];
                                stats: Record<string, never>;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marketplace/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados publicos de confianca e avaliacoes. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Confianca publica. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                reviews?: components["schemas"]["Review"][];
                                professionals?: components["schemas"]["Professional"][];
                                stats?: Record<string, never>;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service_categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista categorias publicas. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categorias. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceCategory"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service_categories/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe publico de uma categoria por slug. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categoria e profissionais ativos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                category?: components["schemas"]["ServiceCategory"];
                                professionals?: components["schemas"]["Professional"][];
                            };
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario autenticado atual. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuario atual. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conta, pedidos recentes e pagamentos recentes. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resumo da conta. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                user?: components["schemas"]["User"];
                                recent_service_requests?: components["schemas"]["ServiceRequest"][];
                                recent_payments?: components["schemas"]["Payment"][];
                            };
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professionals/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pesquisa publica de profissionais por categoria, localizacao administrativa e proximidade.
         * @description Retorna dados publicos dos profissionais. Quando latitude e longitude do cliente sao enviadas, o backend calcula `distance_km`, mas nao revela as coordenadas exatas do profissional.
         */
        get: {
            parameters: {
                query?: {
                    category_slug?: string;
                    province?: string;
                    municipality?: string;
                    neighborhood?: string;
                    /** @description Latitude do cliente quando a localizacao exata for autorizada. */
                    latitude?: number;
                    /** @description Longitude do cliente quando a localizacao exata for autorizada. */
                    longitude?: number;
                    /** @description Raio maximo em quilometros aplicado quando latitude e longitude forem enviados. */
                    radius_km?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profissionais publicos filtrados e, quando possivel, ordenados por distancia. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professionals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista profissionais visiveis pelo usuario autenticado. */
        get: {
            parameters: {
                query?: {
                    category_slug?: string;
                    /** @description Filtro operacional. Ignorado para usuarios nao operacionais. */
                    status?: "online" | "offline" | "occupied" | "suspended";
                    /** @description Filtro operacional por revisao documental. Ignorado para usuarios nao operacionais. */
                    documents_status?: "pending" | "verified" | "rejected";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profissionais. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professionals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de um profissional. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Profissional. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professionals/{id}/operational_profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza estado e notas internas do perfil profissional operacional. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        professional: {
                            /** @enum {string} */
                            status?: "online" | "offline" | "occupied" | "suspended";
                            operator_notes?: string | null;
                        };
                    };
                };
            };
            responses: {
                /** @description Perfil operacional atualizado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/service_requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pedidos visiveis pelo usuario autenticado. */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "assigned" | "accepted" | "in_progress" | "completed" | "cancelled" | "disputed";
                    category_slug?: string;
                    /** @description Filtra a fila operacional por provincia administrativa. */
                    province?: string;
                    urgency?: "normal" | "urgent" | "priority";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pedidos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** Cria pedido de servico. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateServiceRequestInput"];
                    "multipart/form-data": components["schemas"]["CreateServiceRequestInput"] & {
                        attachments?: string[];
                    };
                };
            };
            responses: {
                /** @description Pedido criado. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_portal/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista documentos do profissional autenticado. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Documentos enviados. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProfessionalDocument"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Envia documento de verificacao profissional. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @enum {string} */
                        kind: "identity" | "certificate" | "license";
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Documento recebido. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProfessionalDocument"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_documents/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Aprova ou rejeita documento profissional.
         * @description Apenas usuarios operacionais.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "approved" | "rejected";
                        review_notes?: string;
                    };
                };
            };
            responses: {
                /** @description Documento revisado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ProfessionalDocument"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/service_requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de um pedido. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pedido. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service_requests/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra avaliacao do cliente para um pedido concluido.
         * @description Apenas o cliente dono do pedido pode avaliar, uma vez, depois da conclusao operacional.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateReviewInput"];
                };
            };
            responses: {
                /** @description Avaliacao registrada. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Review"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service_requests/{id}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista candidatos calculados pelo matching. */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Matches. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Match"][];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service_requests/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Atribui profissional a um pedido.
         * @description Apenas usuarios operacionais.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AssignServiceRequestInput"];
                };
            };
            responses: {
                /** @description Pedido atribuido. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/service_requests/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualiza estado do pedido.
         * @description Profissionais atribuidos podem atualizar estados operacionais sem pagamento. O estado `completed`, que gera pagamento pago, e exclusivo para usuarios operacionais.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateServiceRequestStatusInput"];
                };
            };
            responses: {
                /** @description Pedido atualizado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"];
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
    "/api/v1/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pagamentos visiveis pelo usuario autenticado. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagamentos. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: (components["schemas"]["Payment"] & {
                                service_request?: components["schemas"]["ServiceRequest"];
                            })[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard operacional. */
        get: {
            parameters: {
                query?: {
                    /** @description Filtra a trilha de auditoria operacional exibida no dashboard. */
                    audit_action?: "professional_document.reviewed" | "professional.operational_profile_updated" | "service_request.assigned" | "service_request.status_updated";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Indicadores operacionais. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                stats?: components["schemas"]["OperationsStats"];
                                service_quality?: components["schemas"]["OperationsServiceQuality"];
                                risk_alerts?: components["schemas"]["OperationsRiskAlert"][];
                                recent_requests?: components["schemas"]["ServiceRequest"][];
                                top_professionals?: components["schemas"]["Professional"][];
                                categories?: components["schemas"]["ServiceCategory"][];
                                matching_preview_request?: components["schemas"]["ServiceRequest"] | null;
                                matching_preview?: components["schemas"]["Match"][];
                                audit_actions?: string[];
                                recent_audit_logs?: components["schemas"]["AuditActivity"][];
                            };
                        };
                    };
                };
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_portal/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard do profissional. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dados do painel profissional. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_portal/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Carteira do profissional. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pagamentos e totais do profissional. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_portal/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historico de pedidos do profissional. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historico. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_portal/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pedidos pendentes nas categorias do profissional. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vagas. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ServiceRequest"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/professional_portal/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil do profissional autenticado. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Perfil profissional. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        /** Cria perfil do profissional autenticado. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfessionalProfileInput"];
                };
            };
            responses: {
                /** @description Perfil profissional criado. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /** Atualiza perfil do profissional autenticado. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfessionalProfileInput"];
                };
            };
            responses: {
                /** @description Perfil profissional atualizado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Professional"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                422: components["responses"]["ValidationFailed"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: {
                /**
                 * @example unauthorized
                 * @example forbidden
                 * @example not_found
                 * @example validation_failed
                 */
                code: string;
                message: string;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        ServiceCategory: {
            id: number;
            name: string;
            slug: string;
            description?: string | null;
            base_price_cents: number;
            average_duration_minutes: number;
            urgent_available: boolean;
            icon_token: string;
            image_name: string;
            image_path: string;
            professionals_count?: number;
        };
        Client: {
            id: number;
            name: string;
            company_name?: string | null;
            province?: string | null;
            municipality?: string | null;
            neighborhood?: string | null;
            contact?: {
                phone?: string;
                email?: string | null;
            };
            address?: string | null;
            coordinates?: components["schemas"]["Coordinates"];
        };
        Coordinates: {
            latitude?: number | string | null;
            longitude?: number | string | null;
        };
        AuditActivity: {
            id: number;
            /** @enum {string} */
            action: "professional_document.reviewed" | "professional.operational_profile_updated" | "service_request.assigned" | "service_request.status_updated";
            actor?: {
                id?: number;
                name?: string;
                role?: string;
            } | null;
            auditable_type?: string | null;
            auditable_id?: number | null;
            metadata?: {
                [key: string]: string | number | boolean | null;
            };
            /** Format: date-time */
            created_at: string;
        };
        OperationsStats: {
            revenue_cents: number;
            commission_cents: number;
            requests_count: number;
            open_requests_count: number;
            pending_requests_count: number;
            assigned_requests_count: number;
            in_work_requests_count: number;
            disputed_requests_count: number;
            professionals_online_count: number;
            professionals_verified_count: number;
            professionals_available_count: number;
            professionals_pending_docs_count: number;
            professionals_rejected_docs_count: number;
            overdue_requests_count: number;
            sla_risk_requests_count: number;
            average_response_minutes: number | null;
            completion_rate_percent: number | null;
            dispute_rate_percent: number | null;
            average_quality_rating: number | null;
            review_coverage_percent: number | null;
        };
        OperationsServiceQuality: {
            /** @enum {string} */
            status: "healthy" | "attention" | "critical";
            /** Format: date-time */
            generated_at: string;
            overdue_requests_count: number;
            sla_risk_requests_count: number;
            average_response_minutes: number | null;
            completion_rate_percent: number | null;
            dispute_rate_percent: number | null;
            average_quality_rating: number | null;
            review_coverage_percent: number | null;
        };
        OperationsRiskAlert: {
            id: number;
            code: string;
            title: string;
            /** @enum {string} */
            status: "pending" | "assigned" | "accepted" | "in_progress" | "disputed";
            /** @enum {string} */
            urgency: "normal" | "urgent" | "priority";
            province?: string | null;
            service_category_name: string;
            /** Format: date-time */
            scheduled_at?: string | null;
            age_minutes: number;
            /** @enum {string} */
            risk_level: "medium" | "high" | "critical";
            reason: string;
        };
        Professional: {
            id: number;
            name: string;
            specialty: string;
            bio?: string | null;
            location: string;
            province?: string | null;
            municipality?: string | null;
            neighborhood?: string | null;
            /** @enum {string} */
            status: "online" | "offline" | "occupied" | "suspended";
            /** @enum {string} */
            documents_status: "pending" | "verified" | "rejected";
            experience_years: number;
            hourly_rate_cents: number;
            rating: number;
            quality_rating?: number;
            punctuality_rating?: number;
            communication_rating?: number;
            completed_jobs: number;
            distance_km?: number;
            response_minutes?: number;
            service_categories?: components["schemas"]["ServiceCategory"][];
            contact?: {
                phone?: string;
                email?: string | null;
            };
            coordinates?: components["schemas"]["Coordinates"];
            documents?: components["schemas"]["ProfessionalDocument"][];
            /** @description Nota interna visivel apenas para administradores e operadores. */
            operator_notes?: string | null;
            /** @description Historico operacional visivel apenas para administradores e operadores. */
            operational_activity?: components["schemas"]["AuditActivity"][];
        };
        ProfessionalDocument: {
            id: number;
            professional_id: number;
            /** @enum {string} */
            kind: "identity" | "certificate" | "license";
            /** @enum {string} */
            status: "pending" | "approved" | "rejected";
            original_filename: string;
            content_type: string;
            byte_size: number;
            review_notes?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            reviewed_by?: {
                id?: number;
                name?: string;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProfessionalProfileInput: {
            professional: {
                name: string;
                phone: string;
                /** Format: email */
                email?: string;
                specialty: string;
                bio?: string;
                location: string;
                province?: string;
                municipality?: string;
                neighborhood?: string;
                hourly_rate_cents?: number;
                experience_years?: number;
                response_minutes?: number;
                /** @enum {string} */
                status?: "online" | "offline" | "occupied";
                service_category_ids?: number[];
            };
        };
        Payment: {
            id: number;
            service_request_id: number;
            amount_cents: number;
            commission_cents?: number;
            professional_payout_cents?: number;
            /** @enum {string} */
            method: "multicaixa_express" | "unitel_money" | "reference" | "stripe" | "paypal" | "cash";
            /** @enum {string} */
            status: "pending" | "paid" | "refunded" | "failed";
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ServiceRequest: {
            id: number;
            code: string;
            title: string;
            description?: string | null;
            /** @enum {string} */
            status: "pending" | "assigned" | "accepted" | "in_progress" | "completed" | "cancelled" | "disputed";
            /** @enum {string} */
            urgency: "normal" | "urgent" | "priority";
            location: string;
            province?: string | null;
            municipality?: string | null;
            neighborhood?: string | null;
            budget_cents: number;
            /** Format: date-time */
            scheduled_at?: string | null;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            service_category: components["schemas"]["ServiceCategory"];
            client: components["schemas"]["Client"];
            professional?: components["schemas"]["Professional"] | null;
            payments?: components["schemas"]["Payment"][];
            attachments?: components["schemas"]["ServiceRequestAttachment"][];
            review?: components["schemas"]["Review"] | null;
        };
        ServiceRequestAttachment: {
            id: number;
            service_request_id: number;
            original_filename: string;
            content_type: string;
            byte_size: number;
            /** Format: date-time */
            created_at: string;
        };
        Match: {
            professional: components["schemas"]["Professional"];
            score: number;
            distance_km: number;
            rating_score: number;
            proximity_score: number;
            availability_score: number;
            experience_score: number;
        };
        Review: {
            id: number;
            quality: number;
            punctuality: number;
            communication: number;
            comment?: string | null;
            /** Format: date-time */
            created_at: string;
            client: components["schemas"]["Client"];
            professional: components["schemas"]["Professional"];
            service_request: {
                id: number;
                code?: string;
                title: string;
            };
        };
        CreateReviewInput: {
            review: {
                quality: number;
                punctuality: number;
                communication: number;
                comment?: string | null;
            };
        };
        User: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "operator" | "professional" | "client";
            active: boolean;
            profile?: components["schemas"]["Client"] | components["schemas"]["Professional"] | null;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        CreateServiceRequestInput: {
            client: {
                name: string;
                phone: string;
                /** Format: email */
                email?: string;
                company_name?: string;
                address?: string;
                province?: string;
                municipality?: string;
                neighborhood?: string;
                latitude?: number;
                longitude?: number;
            };
            service_request: {
                service_category_id: number;
                title: string;
                description: string;
                location: string;
                province?: string;
                municipality?: string;
                neighborhood?: string;
                latitude?: number;
                longitude?: number;
                /** @enum {string} */
                urgency?: "normal" | "urgent" | "priority";
                /** Format: date-time */
                scheduled_at?: string;
                /** @description Campo interno aceito apenas para usuarios operacionais; clientes e profissionais devem enviar budget_aoa. */
                budget_cents?: number;
                budget_aoa?: number;
                /** @description Campo interno aceito apenas para usuarios operacionais; clientes e profissionais nao conseguem gravar este valor. */
                operator_notes?: string;
            };
        };
        AssignServiceRequestInput: {
            professional_id: number;
        };
        UpdateServiceRequestStatusInput: {
            /** @enum {string} */
            status: "accepted" | "in_progress" | "completed" | "cancelled" | "disputed";
        };
    };
    responses: {
        /** @description Usuario nao autenticado. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Usuario autenticado sem permissao. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso nao encontrado. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Erro de validacao. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
